name: Run tests and publish report
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            java-version: '23'
            distribution: 'temurin'
            architecture: x64
            
        - uses: actions/checkout@v4
        
        - name: Run script
          run: |
                mvn --batch-mode --update-snapshots verify
                mvn allure:aggregate
                
        - name: Publish test report
          uses: peaceiris/actions-gh-pages@v3
          if: always()
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: report
            publish_dir: ./target/site/allure-maven-plugin
