name: Run tests and publish report
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            java-version: '23'
            distribution: 'temurin'
            architecture: x64

        - name: Selenoid
          run: |
                curl -s https://aerokube.com/cm/bash | bash
                chmod +x ./cm | ./cm selenoid start --browsers 'chrome' --last-versions 1
        
        - uses: actions/checkout@v4
        
        - name: Run script
          run: |
                mvn -B -ntp --update-snapshots -DBROWSER=chrome -Dwebdriver.driver=chrome -Dselenide.browser=chrome -Dchrome.switches=--headless -Dselenide.headless=true verify
                mvn -B -ntp allure:aggregate
                
        - name: Publish test report
          uses: peaceiris/actions-gh-pages@v3
          if: always()
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: report
            publish_dir: ./target/site/allure-maven-plugin
